apiVersion: v1
kind: ConfigMap
metadata:
  name: hive-delta-config
  namespace: datahub
data:
  hive-delta-template.yaml: |
    source:
      type: hive-metastore
      config:
        host_port: hive-metastore-postgres-postgresql.hive.svc.cluster.local:5432
        database: postgres
        username: postgres
        password: postgres
        scheme: postgresql+psycopg2
        schema_pattern:
          allow:
            - "^public"
    sink:
      type: datahub-rest
      config:
        server: http://datahub-datahub-gms.minio.svc.cluster.local:8080
        token: $DATAHUB_TOKEN
